apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: gitops
spec:
  project: default

  source:
    repoURL: http://gitlab.gitlab.svc.cluster.local/infrastructure/gitlab.git
    targetRevision: "master"  # Git branch (or tag) for the repo
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab  # The namespace where GitLab will be deployed

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
